### ISSUE TITLE
Remove docs folder from tracking

### ISSUE THREAD

**Issue by aemann2** [openoakland/funding-public-safety#80]
Current behavior: `/docs` is currently a tracked file being uploaded to the repo. Whenever a user makes changes locally, this causes changes in their local docs folder. If a user stages changes with `git add .`, changes in the local docs folder will modify the origin `/docs` folder in the repo.

Proposed behavior: Since the `/docs` folder is created by Github Pages at build time, we should be able to remove it from the repo and from tracking by adding it to `.gitignore`. This way, people working on the site are not directly making changes to the origin `/docs` folder.

  - [ ] Remove `/docs` from tracking
  - [ ] Add `/docs` to gitignore
  - [ ] Add `.DS_Store` to gitignore

**Comment by jaedoak** [comment]
Thank you for this! While you're add it, would you also add .DS_Store to gitignore?

**Comment by aemann2** [comment]
Sure thing! I should have time to get this in early next week.

**Comment by aemann2** [comment]
#102 broke all our images! I reverted that commit and am reopening this.

**Comment by aemann2** [comment]
Fixed in #103
